// APP TYPES

export const INITIALIZE_START = 'INITIALIZE_START';
export const INITIALIZE_END = 'INITIALIZE_END';
export const INITIALIZE_ERROR = 'INITIALIZE_ERROR';

// AUTH TYPES

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_END = 'LOGIN_END';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_TOKEN_START = 'LOGIN_TOKEN_START';
export const LOGIN_TOKEN_END = 'LOGIN_TOKEN_END';
export const LOGIN_TOKEN_ERROR = 'LOGIN_TOKEN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_END = 'LOGOUT_END';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_END = 'REGISTER_END';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const AUTH_GOT_SESSION = 'AUTH_GOT_SESSION';
export const AUTH_CLEAR_MESSAGE = 'AUTH_CLEAR_MESSAGE';
export const AUTH_SET_REDIRECT = 'AUTH_SET_REDIRECT';

// MENU

export const SET_ACTIVE_MENU_ITEM = 'SET_ACTIVE_MENU_ITEM';

// BOOKS

export const GET_BOOKS_START = 'GET_BOOKS_START';
export const GET_BOOKS_END = 'GET_BOOKS_END';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';
