// APP TYPES

export const INITIALIZE_START = 'INITIALIZE_START';
export const INITIALIZE_END = 'INITIALIZE_END';
export const INITIALIZE_ERROR = 'INITIALIZE_ERROR';

// AUTH TYPES

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_END = 'LOGIN_END';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_TOKEN_START = 'LOGIN_TOKEN_START';
export const LOGIN_TOKEN_END = 'LOGIN_TOKEN_END';
export const LOGIN_TOKEN_ERROR = 'LOGIN_TOKEN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_END = 'LOGOUT_END';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_END = 'REGISTER_END';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const AUTH_GOT_SESSION = 'AUTH_GOT_SESSION';
export const AUTH_SET_REDIRECT = 'AUTH_SET_REDIRECT';

// MENU

export const SET_ACTIVE_MENU_ITEM = 'SET_ACTIVE_MENU_ITEM';

// BOOKS

export const GET_BOOKS_START = 'GET_BOOKS_START';
export const GET_BOOKS_END = 'GET_BOOKS_END';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

export const GET_BOOK_BY_ID_START = 'GET_BOOK_BY_ID_START';
export const GET_BOOK_BY_ID_END = 'GET_BOOK_BY_ID_END';
export const GET_BOOK_BY_ID_ERROR = 'GET_BOOK_BY_ID_ERROR';

export const FAVOURITE_BOOKS_START = 'FAVOURITE_BOOKS_START';
export const FAVOURITE_BOOKS_END = 'FAVOURITE_BOOKS_END';
export const FAVOURITE_BOOKS_ERROR = 'FAVOURITE_BOOKS_ERROR';

export const DELETE_BOOKS_START = 'DELETE_BOOKS_START';
export const DELETE_BOOKS_END = 'DELETE_BOOKS_END';
export const DELETE_BOOKS_ERROR = 'DELETE_BOOKS_ERROR';

export const UPLOAD_BOOKS_START = 'UPLOAD_BOOKS_START';
export const UPLOAD_BOOKS_END = 'UPLOAD_BOOKS_END';
export const UPLOAD_BOOKS_ERROR = 'UPLOAD_BOOKS_ERROR';

export const UPDATE_BOOK_THUMBNAIL_START = 'UPDATE_BOOK_THUMBNAIL_START';
export const UPDATE_BOOK_THUMBNAIL_END = 'UPDATE_BOOK_THUMBNAIL_END';
export const UPDATE_BOOK_THUMBNAIL_ERROR = 'UPDATE_BOOK_THUMBNAIL_ERROR';

// TOASTS

export const TOAST_DISMISS = 'TOAST_DISMISS';
export const TOAST_ADD = 'TOAST_ADD';